application.name=Workflow Persistence Engine

application.version=1.0.0-SNAPSHOT

database.host=localhost
database.port=5432
database.name=workflow_engine
database.username=postgres
database.password=PujaSQL@2006